version: '3'
services:
 jenkinsci-master:
  build:
   context: . 
   dockerfile: master
  expose:
   - 50000
  ports:
   - 8080:8080
  volumes:
   - $HOME/jenkins:/var/jenkins_home
   
 jenkinsci-slave:
  build:
   context: . 
   dockerfile: slave
  env_file: env
  volumes:
   - $HOME/jenkins/slave:/home/jenkins
  depends_on:
   - jenkinsci-master
  links:
   - jenkinsci-master

 jenkins-docker:
  image: alpine/socat
  ports:
   - 2375:2375
  volumes:
   -  /var/run/docker.sock:/var/run/docker.sock
  command: TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock

