version: '3'
services:
 jenkinsci-master:
  build:
   context: . 
   dockerfile: master
  expose:
   - 50000
  ports:
   - 8080:8080
  volumes:
   - $HOME/jenkins:/var/jenkins_home
   
 jenkinsci-slave:
  build:
   context: . 
   dockerfile: slave
  env_file: env
  volumes:
   - $HOME/jenkins/slave:/home/jenkins
  depends_on:
   - jenkinsci-master
  links:
   - jenkinsci-master
