version: '3'
services:
 jenkinsci-master:
  build: .
  #expose:
  # - 50000
  ports:
   - 8080:8080
  volumes:
   - $HOME/jenkins:/var/jenkins_home
   - $HOME/jenkins/ssh:/tmp/ssh


 jenkinsci-slave:
  image: jenkinsci/ssh-slave
  #env_file: env
  volumes:
   - $HOME/jenkins/slave:/home/jenkins
   - $HOME/jenkins/ssh/id_rsa.pub:/home/jenkins/.ssh/authorized_keys
  depends_on:
   - jenkinsci-master
  links:
   - jenkinsci-master
